In [1]:
import numpy as np

#### 1. Write a NumPy program to create an array with the values 1, 7, 13, 105    and determine the size of the memory occupied by the array.

In [10]:
arr1 = np.array([1, 7, 13, 105])
print(f"Size of array 'arr1': {arr1.nbytes}")

[  1   7  13 105]
Size of array 'arr1': 32


#### 2. Write a NumPy program to create an element-wise comparison (greater,    greater_equal, less and less_equal) of two given arrays.

#### 3.  Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 10 twentys and 10 fiftys.

In [6]:
arr3 = np.zeros(10, dtype=np.int8)
print(arr3)
arr3 = np.ones(10, dtype=np.int8)
print(arr3)
arr3 = np.ones(10, dtype=np.int8) * 5
print(arr3)
arr3 = np.ones(10, dtype=np.int8) * 10
print(arr3)
arr3 = np.ones(10, dtype=np.int8) * 20
print(arr3)
arr3 = np.ones(10, dtype=np.int8) * 50
print(arr3)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]
[10 10 10 10 10 10 10 10 10 10]
[20 20 20 20 20 20 20 20 20 20]
[50 50 50 50 50 50 50 50 50 50]


#### 4. Write a NumPy program to create an array of integers from 30 to 70.

In [8]:
arr4 = np.arange(30, 71)
print(arr4)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


#### 5. Write a NumPy program to create an array of integers from 50 to 95.

In [13]:
arr5 = np.arange(50, 96)
print(arr5)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


#### 6. Write a NumPy program to create an array of all even integers from 20 to 80.

In [14]:
arr6 = np.arange(20, 81, 2)
print(arr6)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80]


#### 7. Write a NumPy program to create an array of all odd integers from 20 to 80.

In [30]:
arr7 = np.arange(21, 81, 2)
print(arr7)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


#### 8. Write a NumPy program to generate an array of 15 random numbers from 10    to 40.

In [17]:
arr8 = np.random.randint(10, 40, 15)
print(arr8)

[17 35 28 30 16 37 31 16 38 10 38 18 22 31 34]


#### 9. Write a NumPy program to generate an array of 10 random numbers from 30    to 50.

In [ ]:
arr9 = np.random.randint(30, 50, 10)
print(arr9)

#### 10. Write a NumPy program to generate an array of 20 random numbers from 50    to 90.

In [24]:
arr10 = np.random.randint(50, 90, 20)
print(arr10)

[85 74 54 57 61 52 66 67 64 88 71 64 52 69 83 86 80 84 66 83]


#### 11. Create any two arrays & perform various mathematical operations.    i.e. Addition, Substraction, Multiplication, Divide.


#### 12. Write a NumPy program to create a 3x4 matrix filled with values from 10     to 21.

In [50]:
arr12 = np.arange(10, 22)
arr = arr12.reshape([3, 4])
print(arr)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


#### 13. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal     elements are 1, the rest are 0.

In [56]:
list13 = []
for i in range(3):
    for j in range(3):
        if i == j:
            list13.append(1)
        else:
            list13.append(0)
arr13 = np.array(list13)
arr13 = arr13.reshape([3, 3])
print(arr13)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 14. Write a NumPy program to find the number of rows and columns in a given     matrix. 

In [57]:
dimensions = arr13.shape
print(f"rows = {dimensions[0]}, columns = {dimensions[1]}")

rows = 3, columns = 3


#### 15. Write a NumPy program to create a 5x5 zero matrix with elements on the     main diagonal equal to 1, 2, 3, 4, 5.

In [70]:
arr15 = np.zeros([5, 5], dtype=np.int8)
diag_element = 1
for i in range(5):
    for j in range(5):
        if i == j:
            arr15[i][j] = diag_element
            diag_element += 1
            
print(arr15)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 16. Write a NumPy program to create a 3x3x3 array filled with arbitrary     values.

#### 17. Write a NumPy program to create a 2x3x4 array filled with arbitrary     values.

#### 18. Write a NumPy program to convert a list of numeric values into a one-    dimensional NumPy array.

In [33]:
list18 = [13, 32, 54, 23, 56, 4, 76]
arr18 = np.array(list18)
print(arr18)

[13 32 54 23 56  4 76]


#### 19. Write a NumPy program to create a 3x3 matrix with values ranging from 2     to 10.

In [73]:
arr19 = np.arange(2, 11)
arr19 = arr19.reshape([3, 3])
print(arr19)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


#### 20. Write a NumPy program to create an array with values ranging from 12 to 38.

In [74]:
arr20 = np.arange(12, 39)
print(arr20)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


#### 21. Write a NumPy program to reverse an array (the first element becomes the last).

#### 22. Write a NumPy program to convert an data type into to a floating type.

#### 23. Write a NumPy program to convert a list array.

#### 24. Write a NumPy program to get the element-wise remainder of an array of division.

#### 25. Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.